In [1]:
!pip install numpy


In [2]:
import numpy as np
print(np.__version__)

2.1.3


In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
import numpy as np
lis= [1,2,3,4,5]
arr = np.array(lis)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [6]:
import numpy as np
arr=np.array(5)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
5


In [8]:
import numpy as np
arr = np.array([[1,2,3,4,5,],[10,20,30,40,50]])
print(arr)


[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [10]:
import pandas as pd
mydataset = {
  'name': ["ram", "shyam", "sita"],
  'age': [3, 7, 2]
}
myvar = pd.DataFrame(mydataset)
print(myvar)



NameError: name 'pandas' is not defined