In [6]:
import numpy as np

arr1 = np.array([4,5,6])
print(arr1)

[4 5 6]


In [7]:
print(type(arr1))

<class 'numpy.ndarray'>


In [8]:
print(arr1.shape)

(3,)


In [9]:
print(arr1[2])

6


In [10]:
arr1[1]=9
arr1

array([4, 9, 6])

In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2[1,2]

np.int64(6)

In [13]:
print(arr2.shape)

(2, 3)


In [14]:
arr2[1][-2]

np.int64(5)

In [15]:
arrM = np.arange(0,30,3)
arrM

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [16]:
arrL = np.linspace(0,15,30)
arrL

array([ 0.        ,  0.51724138,  1.03448276,  1.55172414,  2.06896552,
        2.5862069 ,  3.10344828,  3.62068966,  4.13793103,  4.65517241,
        5.17241379,  5.68965517,  6.20689655,  6.72413793,  7.24137931,
        7.75862069,  8.27586207,  8.79310345,  9.31034483,  9.82758621,
       10.34482759, 10.86206897, 11.37931034, 11.89655172, 12.4137931 ,
       12.93103448, 13.44827586, 13.96551724, 14.48275862, 15.        ])

In [17]:
arr = np.random.rand(8)
arr

array([0.27543837, 0.37610046, 0.19747781, 0.53616043, 0.45208535,
       0.99419227, 0.38031134, 0.57666714])

In [18]:
print(np.zeros(8))
print('/n')
print(np.zeros((3,4)))

[0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [19]:
print(np.ones((4,2,4)))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [20]:
arr = [0, 1, 2]
print(np.repeat(arr,4))

[0 0 0 0 1 1 1 1 2 2 2 2]
